### ISSUE TITLE
Smart groups broken on disable / enable

### ISSUE THREAD

**Issue by khorporative** [progressivetech/net.ourpowerbase.sumfields#52]
If I disable and re-enable Summary Fields, the Smart Groups that contain Summary Fields custom fields in search are broken. As are all those Smart Groups that contain / refer to Smart Groups that search custom fields of Summary Fields.

![image](https://user-images.githubusercontent.com/18428628/55278904-1b5fdb00-531b-11e9-9e85-167702c6acef.png)

**Comment by jmcclelland** [comment]
Thanks for the report. That seems to be because I was destroying the tables on disable rather than just disabling them. I guess I figured there should not be any useful data in them so it was ok.

In any event, I just updated the code so now when you disable, the custom fields are disabled. When you enable, they are re-enabled.

Since they are no longer destroyed, they will retain the same field names, which should allow your smart groups to keep working properly.
