### ISSUE TITLE
after upgrade to civicrm 5.32.2, sumfields won't save its own settings

### ISSUE THREAD

**Issue by twomice** [progressivetech/net.ourpowerbase.sumfields#84]
Summary Fields version 4.0.2

I upgraded civicrm to version 5.32.2 on Drupal 8. Soon after, we noticed all Summary Fields had empty values.

I went as far as completely re-installing summary fields:

1. uninstall the extension
2. verify the "Summary Fields" custom field group does not exist (it does not)
3. enable the extension.
4. verify the "Summary Fields" custom field group does exist (it does).
5. visit https://[example].org/civicrm/admin/setting/sumfields and observe setting form opens fine. Select a checkbox to any field (e.g. "Total Lifetime Contributions"), and save the form.
6. Observe the settings form re-loads, and my settings are not saved (the "Total Lifetime Contributions" check-box is not checked).
7. Examine the "Summary Fields" custom data group; observe it contains no fields.

I'm at a loss. Is it possible SumFields doesn't work under civicrm 5.32.2?

**Comment by jmcclelland** [comment]
It's possible - I haven't tested it yet. I'll be working on compatability with 5.33 in the coming weeks though - so that should catch any problems with 5.32 I suspect.

**Comment by twomice** [comment]
Thanks @jmcclelland FYI, behavior described in the OP continues with the latest github master branch.

**Comment by twomice** [comment]
@jmcclelland I didn't expect this, but it appears that I have to choose _When should these changes be applied?: When I submit this form_ in order to see the saved settings appearing in the form. Is that normal behavior by-design?

**Comment by jmcclelland** [comment]
Yes - that's by design. On some sites/server, the browser/web server could time out waiting for the summary fields data to be calculated. So, if you choose the option to run that on a cron job you don't have to worry about browser time out issues. But, you do have to be sure the scheduled job is set and you have to wait for it to execute.

**Comment by twomice** [comment]
Thanks @jmcclelland. Just to clarify, this by-design behavior also includes the fact that my configurations, though saved somewhere, don't appear in the settings form until that Scheduled Job fires?

**Comment by jmcclelland** [comment]
Sorry - I didn't properly answer your question. In my defense, there is some serious nuance going on here :).

The answer is still the same - yes, it is by design. 

I don't claim it's the *best* design. But it's not easy to communicate changes that are scheduled but not active. Right now, the page shows you which fields are currently active right now, but hides what is going to be active after the next cron job. We could do the opposite, but that is also confusing because people might think they are active when they aren't.

Perhaps the easiest change would be to change the status message, which currently is: Setting changes were saved on 2021-02-08 08:58:18, but not yet applied; they should be applied shortly. 

It could instead be something like: Setting changes were saved on 2021-02-08 08:58:18, but not yet applied; they should be applied shortly.  The settings below reflect the old settings. They will be updated to reflect the new settings after the change is applied.

And the best change could be to put a red asterisks or something next to fields that are different in the new version compared with the old version to indicate that they are not up to date.  Or other ideas?

**Comment by twomice** [comment]
Yes, definitely nuanced, and thanks Jamie for helping me sort this out. I think your suggestions are a big step up in helping to clarify the "interim" status to the user. I imagine there's some complexity there, as ideally you'd be trying to identify "un-applied" settings that can include enabled/disabled fields as well as changes in the option settings such as Financial Type. 

In any case, your patient explanation has resolve the issue in this ticket. Please feel free to close it. Thanks!

**Comment by jmcclelland** [comment]
Sure thing!
