### ISSUE TITLE
Uninstall sql invalid in 4.7

### ISSUE THREAD

**Issue by eileenmcnaughton** [progressivetech/net.ourpowerbase.sumfields#9]
DELETE FROM civicrm_setting WHERE group_name = 'Summary Fields' [nativecode=1054 ** Unknown column 'group_name' in 'where clause']

Note you probably need to define the settings metadata per https://wiki.civicrm.org/confluence/display/CRMDOC/Settings+Reference

**Comment by fulltrucker** [comment]
I am having trouble uninstalling this extension in 4.6.14.2 as well. The custom data fields (and triggers?) are still intact after uninstalling. Custom data fields aren't wanting to delete manually, either.

**Comment by jmcclelland** [comment]
Should now be fixed with commit bb89a4bdb488b8244339b14a8274466a142050c4

I also attempted to accomplish what Eileen submitted with this PR: 
https://github.com/progressivetech/net.ourpowerbase.sumfields/pull/16/

fulltrucker: i suspect the problem you are having might be about your database being in an inconsistent state - if you can't delete the manually, then the uninstall system won't be able to do it either.
